name: Example Workflow

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    # IMPORTANT: to use our self-hosted runner set, you must specify this runs-on key
    runs-on: arc-runner-set

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
